export const products = [
  {
    id: "1",
    name: "Nemlendirici Yüz Kremi",
    description: "Kuru ciltler için 24 saat nemlendirici etkili yüz kremi. İçeriğindeki hyaluronik asit ve vitamin E sayesinde cildinizi derinlemesine nemlendirir ve kuruluğa bağlı oluşan çizgileri azaltır. Özel formülü ile cildin nem bariyerini güçlendirerek dış etkenlere karşı koruma sağlar. Parfümsüz içeriği ile hassas ciltler için uygundur ve günlük bakım rutininizde güvenle kullanabilirsiniz.",
    price: 129,
    brand: "Neutrogena",
    category: "Cilt Bakımı",
    inStock: true,
    image: "https://images.unsplash.com/photo-1556229174-5e42a09e45af?auto=format&fit=crop&q=80",
    reviews: [
      {
        id: "r1a2b3c4d5e6f",
        userId: "u123456789",
        productId: "1",
        rating: 5,
        comment: "Cildim çok kuru ve hassastı. Bu krem sayesinde artık kaşınma ve pullanma yaşamıyorum. Kesinlikle tavsiye ederim!",
        createdDate: "2024-02-15T14:23:45.067Z",
        user: {
          id: "u123456789",
          name: "Ayşe Yılmaz",
          email: "ayse.yilmaz@gmail.com",
          emailVerified: null,
          image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png",
          hashedPassword: null,
          createdAt: "2023-08-12T09:45:23.979Z",
          updatedAt: "2023-08-12T09:45:23.979Z",
          role: "USER",
        },
      },
      {
        id: "r7g8h9i0j1k2",
        userId: "u987654321",
        productId: "1",
        rating: 4,
        comment: "Gerçekten nemlendirici etkisi yüksek ama kokusu biraz rahatsız edici olabiliyor. Yine de fiyatına göre kaliteli bir ürün.",
        createdDate: "2024-03-10T18:12:33.067Z",
        user: {
          id: "u987654321",
          name: "Mehmet Kaya",
          email: "mehmet.kaya@gmail.com",
          emailVerified: null,
          image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png",
          hashedPassword: null,
          createdAt: "2023-05-20T11:32:18.979Z",
          updatedAt: "2023-05-20T11:32:18.979Z",
          role: "USER",
        },
      },
    ],
  },
  {
    id: "2",
    name: "Mat Ruj",
    description: "Uzun süre kalıcı mat bitişli likit ruj. Zengin pigmentli yapısı ile tek sürmede yoğun renk verir ve günlük kullanımda 8 saate kadar kalıcılık sağlar. Özel formülü sayesinde dudaklarınızı kurutmaz ve pürüzsüz bir bitişle gün boyu tazeliğini korur. Yemek ve içecek tüketiminden sonra bile renk vermez ve bulaşma yapmaz. 15 farklı renk seçeneği ile her tarzı tamamlayacak bir ton bulabilirsiniz.",
    price: 89,
    brand: "MAC",
    category: "Makyaj",
    inStock: true,
    image: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&q=80",
    reviews: [
      {
        id: "r3l4m5n6o7p8",
        userId: "u567891234",
        productId: "2",
        rating: 5,
        comment: "Bu ruj gerçekten çok kalıcı! Kahve içtikten sonra bile dudağımda duruyor ve rengi çok güzel.",
        createdDate: "2024-01-25T09:34:20.067Z",
        user: {
          id: "u567891234",
          name: "Zeynep Demir",
          email: "zeynep.demir@gmail.com",
          emailVerified: null,
          image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png",
          hashedPassword: null,
          createdAt: "2023-11-05T15:23:42.979Z",
          updatedAt: "2023-11-05T15:23:42.979Z",
          role: "USER",
        },
      },
    ],
  },
  {
    id: "3",
    name: "Güneş Koruyucu Krem SPF50",
    description: "Yüksek koruma faktörlü, suya dayanıklı güneş kremi. Hem UVA hem de UVB ışınlarına karşı geniş spektrumlu koruma sağlayarak cilt yaşlanmasını önler ve güneş yanıklarını engeller. Hafif ve yağsız formülü ciltte beyaz iz bırakmadan hızla emilir ve makyaj altında da rahatlıkla kullanılabilir. İçeriğindeki antioksidanlar ve E vitamini ile cildi serbest radikallere karşı korurken nem dengesini de sağlar. Suya ve terlemeye karşı 80 dakika dayanıklıdır, plaj ve yüzme aktiviteleri için ideal bir koruma sunar.",
    price: 149,
    brand: "La Roche-Posay",
    category: "Güneş Bakımı",
    inStock: true,
    image: "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&q=80",
    reviews: [],
  },
  {
    id: "4",
    name: "Sıkılaştırıcı Göz Serumu",
    description: "Göz çevresindeki ince çizgileri azaltan ve sıkılaştıran serum. Özel peptid kompleksi ile göz çevresindeki kollajen üretimini uyararak cildin elastikiyetini artırır ve yaşlanma belirtilerini gözle görülür şekilde azaltır. İçeriğindeki hyaluronik asit ve kafein sayesinde şişkinliği giderir, koyu halkaları aydınlatır ve anında bir tazelik etkisi yaratır. Hafif ve ipeksi dokusu sayesinde göz çevresi cildi tarafından hızla emilir ve makyaj öncesinde mükemmel bir baz oluşturur. Oftalmolojik olarak test edilmiştir ve lens kullanıcıları için de uygundur.",
    price: 215,
    brand: "Clinique",
    category: "Cilt Bakımı",
    inStock: false,
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80",
    reviews: [
      {
        id: "r9q0r1s2t3u4",
        userId: "u345678912",
        productId: "4",
        rating: 3,
        comment: "Ürün güzel ancak fiyatı biraz yüksek. Bir aydan fazla kullandım ama çok belirgin etkileri göremedim henüz.",
        createdDate: "2024-03-05T22:17:54.067Z",
        user: {
          id: "u345678912",
          name: "Ahmet Şahin",
          email: "ahmet.sahin@gmail.com",
          emailVerified: null,
          image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png",
          hashedPassword: null,
          createdAt: "2023-07-18T14:25:37.979Z",
          updatedAt: "2023-07-18T14:25:37.979Z",
          role: "USER",
        },
      },
      {
        id: "r5v6w7x8y9z0",
        userId: "u789123456",
        productId: "4",
        rating: 5,
        comment: "45 yaşındayım ve göz çevremdeki ince çizgiler için kullanıyorum. 2 ay sonra fark edilir iyileşme oldu.",
        createdDate: "2024-02-28T13:45:11.067Z",
        user: {
          id: "u789123456",
          name: "Fatma Öztürk",
          email: "fatma.ozturk@gmail.com",
          emailVerified: null,
          image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png",
          hashedPassword: null,
          createdAt: "2023-06-30T17:12:43.979Z",
          updatedAt: "2023-06-30T17:12:43.979Z",
          role: "USER",
        },
      },
      {
        id: "r1a2b3c4d5e7",
        userId: "u123456780",
        productId: "4",
        rating: 4,
        comment: "İlk başta biraz acıtıyor ama sonra alışıyorsunuz. Etkisini 3. haftada görmeye başladım.",
        createdDate: "2024-03-15T08:22:19.067Z",
        user: {
          id: "u123456780",
          name: "Mustafa Yıldız",
          email: "mustafa.yildiz@gmail.com",
          emailVerified: null,
          image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png",
          hashedPassword: null,
          createdAt: "2023-09-05T10:34:27.979Z",
          updatedAt: "2023-09-05T10:34:27.979Z",
          role: "USER",
        },
      },
    ],
  },
  // {
  //   id: "5",
  //   name: "Kapatıcı",
  //   description: "Kusurları ve göz altı morluklarını etkili şekilde kapatan kapatıcı",
  //   price: 95,
  //   brand: "Maybelline",
  //   category: "Makyaj",
  //   inStock: true,
  //   image: "https://images.unsplash.com/photo-1631730359585-38a358764614?auto=format&fit=crop&q=80",
  //   reviews: [],
  // },
  // {
  //   id: "6",
  //   name: "Arındırıcı Yüz Temizleme Jeli",
  //   description: "Gözenekleri arındıran ve yağlı cildi dengeleyen temizleme jeli",
  //   price: 79,
  //   brand: "Garnier",
  //   category: "Cilt Bakımı",
  //   inStock: true,
  //   image: "https://images.unsplash.com/photo-1633683395897-ed5f65c11992?auto=format&fit=crop&q=80",
  //   reviews: [
  //     {
  //       id: "r6f7g8h9i0j1",
  //       userId: "u234567891",
  //       productId: "6",
  //       rating: 5,
  //       comment: "Yağlı cilt sorunumu büyük ölçüde çözdü. Cildimdeki gözenekler gözle görülür şekilde küçüldü.",
  //       createdDate: "2024-01-10T19:28:13.067Z",
  //       user: {
  //         id: "u234567891",
  //         name: "Elif Yalçın",
  //         email: "elif.yalcin@gmail.com",
  //         emailVerified: null,
  //         image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png",
  //         hashedPassword: null,
  //         createdAt: "2023-10-12T12:48:36.979Z",
  //         updatedAt: "2023-10-12T12:48:36.979Z",
  //         role: "USER",
  //       },
  //     },
  //   ],
  // },
  {
    id: "7",
    name: "Saç Bakım Serumu",
    description: "Yıpranmış saçlar için onarıcı ve güçlendirici etkili serum. Keratinle zenginleştirilmiş formülü ile saç tellerini içten dışa yeniler ve kırılmalarını önleyerek daha güçlü bir yapı kazandırır. İçeriğindeki argan yağı ve E vitamini saçlara parlak ve ipeksi bir görünüm verirken, termal koruma özellikleri sayesinde saçlarınızı fön, düzleştirici ve maşa gibi şekillendirici aletlerin ısısına karşı korur. Durulama gerektirmeden kullanılabilir ve her saç tipine uygun hafif yapısı ile saçları ağırlaştırmaz. Düzenli kullanımda saçlardaki elektriklenmeleyi azaltır ve kontrol edilmesi zor saçları kolayca şekillendirilebilir hale getirir.",
    price: 175,
    brand: "Kerastase",
    category: "Saç Bakımı",
    inStock: true,
    image: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&q=80",
    reviews: [],
  },
  // {
  //   id: "8",
  //   name: "Fondöten",
  //   description: "Doğal ve mat görünüm sağlayan uzun süre kalıcı fondöten",
  //   price: 159,
  //   brand: "Estee Lauder",
  //   category: "Makyaj",
  //   inStock: true,
  //   image: "https://images.unsplash.com/photo-1614159102522-26f8a9a3f98c?auto=format&fit=crop&q=80",
  //   reviews: [
  //     {
  //       id: "r2k3l4m5n6o7",
  //       userId: "u456789123",
  //       productId: "8",
  //       rating: 4,
  //       comment: "Kapatıcılığı harika ama biraz kalın uygulanabiliyor, dağıtması zor.",
  //       createdDate: "2024-01-05T11:39:27.067Z",
  //       user: {
  //         id: "u456789123",
  //         name: "Selin Aksoy",
  //         email: "selin.aksoy@gmail.com",
  //         emailVerified: null,
  //         image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png",
  //         hashedPassword: null,
  //         createdAt: "2023-08-25T08:56:14.979Z",
  //         updatedAt: "2023-08-25T08:56:14.979Z",
  //         role: "USER",
  //       },
  //     },
  //     {
  //       id: "r8p9q0r1s2t3",
  //       userId: "u891234567",
  //       productId: "8",
  //       rating: 5,
  //       comment: "Hayatımda kullandığım en iyi fondöten. Rengi cildime çok uygun ve akşama kadar kalıyor.",
  //       createdDate: "2024-03-20T15:43:51.067Z",
  //       user: {
  //         id: "u891234567",
  //         name: "Berk Özcan",
  //         email: "berk.ozcan@gmail.com",
  //         emailVerified: null,
  //         image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png",
  //         hashedPassword: null,
  //         createdAt: "2023-11-15T16:28:39.979Z",
  //         updatedAt: "2023-11-15T16:28:39.979Z",
  //         role: "USER",
  //       },
  //     },
  //   ],
  // },
  // {
  //   id: "9",
  //   name: "Parfüm 50ml",
  //   description: "Çiçeksi ve odunsu notalar içeren uzun süre kalıcı kadın parfümü",
  //   price: 320,
  //   brand: "Chanel",
  //   category: "Parfüm",
  //   inStock: true,
  //   image: "https://images.unsplash.com/photo-1619994403073-2cec99c800d2?auto=format&fit=crop&q=80",
  //   reviews: [
  //     {
  //       id: "r4u5v6w7x8y9",
  //       userId: "u678912345",
  //       productId: "9",
  //       rating: 5,
  //       comment: "Harika bir koku, çok kalıcı ve zarif. Herkes nerede aldığımı soruyor.",
  //       createdDate: "2024-02-12T16:54:32.067Z",
  //       user: {
  //         id: "u678912345",
  //         name: "Deniz Koç",
  //         email: "deniz.koc@gmail.com",
  //         emailVerified: null,
  //         image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png",
  //         hashedPassword: null,
  //         createdAt: "2023-09-18T13:47:25.979Z",
  //         updatedAt: "2023-09-18T13:47:25.979Z",
  //         role: "USER",
  //       },
  //     },
  //   ],
  // },
  {
    id: "10",
    name: "Erkek Parfüm 100ml",
    description: "Ferah ve baharatlı notalar içeren erkek parfümü. Üst notalarda canlandırıcı limon ve yeşil elma, orta notalarda egzotik karabiber ve tütün, alt notalarda ise etkileyici deri ve amber notaları ile maskülen bir karakter taşır. Hem ofis ortamı hem de özel davetler için ideal olan dengeli yapısı ile her yaştan erkeğe hitap eder. Uzun süre kalıcı formülü sayesinde gün boyu ferahlık ve çekicilik sağlar, aynı zamanda farklı mevsimlerde de kullanılabilecek kadar çok yönlüdür. Şık ve maskülen tasarımlı şişesi ile erkeklerin tuvalet masasında göz alıcı bir detay olarak yerini alır.",
    price: 280,
    brand: "Hugo Boss",
    category: "Parfüm",
    inStock: false,
    image: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&q=80",
    reviews: [],
  },
  {
    id: "11",
    name: "Göz Farı Paleti",
    description: "12 farklı renk içeren mat ve simli göz farı paleti. Her türlü göz makyajı için ihtiyaç duyacağınız nötr tonlardan cesur renklere kadar geniş bir renk yelpazesi sunar. Yüksek pigmentli formülü ile tek sürüşte yoğun renk verir ve gün boyu dağılmadan kalıcılığını korur. İçeriğindeki özel bağlayıcılar sayesinde renklerin canlılığını kaybetmeden 10 saate kadar dayanır ve kolay hareli geçişler sağlar. Yumuşak ve ipeksi dokulu fırçası ile profesyonel sonuçlar elde etmenizi sağlayan bu palet, hem gündüz hem de gece makyajları için ideal bir seçimdir.",
    price: 199,
    brand: "Urban Decay",
    category: "Makyaj",
    inStock: true,
    image: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&q=80",
    reviews: [
      {
        id: "r0z1a2b3c4d5",
        userId: "u912345678",
        productId: "11",
        rating: 4,
        comment: "Renkler çok pigmentli ama bazıları dağılabiliyor. Yine de günlük makyajda kolayca kullanılabilir.",
        createdDate: "2024-03-02T10:15:43.067Z",
        user: {
          id: "u912345678",
          name: "Canan Doğan",
          email: "canan.dogan@gmail.com",
          emailVerified: null,
          image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png",
          hashedPassword: null,
          createdAt: "2023-10-08T09:37:46.979Z",
          updatedAt: "2023-10-08T09:37:46.979Z",
          role: "USER",
        },
      },
      {
        id: "r6e7f8g9h0i1",
        userId: "u345678901",
        productId: "11",
        rating: 5,
        comment: "Bu palette her türlü göz makyajı yapabilirsiniz. Özellikle simli tonlar çok etkileyici.",
        createdDate: "2024-01-18T17:29:38.067Z",
        user: {
          id: "u345678901",
          name: "Esra Aydın",
          email: "esra.aydin@gmail.com",
          emailVerified: null,
          image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png",
          hashedPassword: null,
          createdAt: "2023-07-22T18:53:21.979Z",
          updatedAt: "2023-07-22T18:53:21.979Z",
          role: "USER",
        },
      },
    ],
  },
  // {
  //   id: "12",
  //   name: "Akne Karşıtı Tonik",
  //   description: "Sivilce ve siyah noktalara karşı etkili arındırıcı tonik",
  //   price: 85,
  //   brand: "The Ordinary",
  //   category: "Cilt Bakımı",
  //   inStock: true,
  //   image: "https://images.unsplash.com/photo-1611080541675-61967df958e4?auto=format&fit=crop&q=80",
  //   reviews: [
  //     {
  //       id: "r2j3k4l5m6n7",
  //       userId: "u567890123",
  //       productId: "12",
  //       rating: 3,
  //       comment: "Sivilcelerimi azalttı ama cildimi biraz kuruttu. Hassas ciltliler dikkatli kullanmalı.",
  //       createdDate: "2024-02-20T14:17:55.067Z",
  //       user: {
  //         id: "u567890123",
  //         name: "Burak Tekin",
  //         email: "burak.tekin@gmail.com",
  //         emailVerified: null,
  //         image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png",
  //         hashedPassword: null,
  //         createdAt: "2023-08-14T07:42:19.979Z",
  //         updatedAt: "2023-08-14T07:42:19.979Z",
  //         role: "USER",
  //       },
  //     },
  //   ],
  // },
  // {
  //   id: "13",
  //   name: "Saç Şampuanı",
  //   description: "Boyalı saçlar için renk koruyucu ve besleyici şampuan",
  //   price: 69,
  //   brand: "L'Oreal",
  //   category: "Saç Bakımı",
  //   inStock: true,
  //   image: "https://images.unsplash.com/photo-1631730357933-93d4ce3715ff?auto=format&fit=crop&q=80",
  //   reviews: [],
  // },
  {
    id: "14",
    name: "Hyaluronik Asit Serum",
    description: "Yoğun nemlendirici etkili hyaluronik asit içeren yüz serumu. Üç farklı molekül ağırlığındaki hyaluronik asit sayesinde cildin farklı katmanlarına nüfuz ederek derinlemesine ve uzun süreli nem sağlar. İçeriğindeki B5 vitamini cildin nem tutma kapasitesini artırırken, aynı zamanda cilt bariyerinin güçlenmesine yardımcı olur. Hafif ve sulu yapısı ile hızla emilir, yapışkan bir his bırakmaz ve makyaj öncesinde mükemmel bir baz görevi görür. Tüm cilt tiplerine uygun olan bu serum, ciltteki ince çizgilerin ve kuruluk belirtilerinin görünümünü azaltarak daha dolgun ve canlı bir cilt görünümü sağlar.",
    price: 125,
    brand: "The Ordinary",
    category: "Cilt Bakımı",
    inStock: true,
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80",
    reviews: [
      {
        id: "r8o9p0q1r2s3",
        userId: "u789012345",
        productId: "14",
        rating: 5,
        comment: "Cildimdeki kuruluk sorunu tamamen geçti. Artık makyajım daha düzgün duruyor ve cildim ışıldıyor.",
        createdDate: "2024-03-08T21:36:44.067Z",
        user: {
          id: "u789012345",
          name: "Gizem Çelik",
          email: "gizem.celik@gmail.com",
          emailVerified: null,
          image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png",
          hashedPassword: null,
          createdAt: "2023-11-30T10:25:17.979Z",
          updatedAt: "2023-11-30T10:25:17.979Z",
          role: "USER",
        },
      },
      {
        id: "r4t5u6v7w8x9",
        userId: "u890123456",
        productId: "14",
        rating: 4,
        comment: "Fiyat/performans olarak mükemmel bir ürün. Kremlerden önce kullanınca daha etkili oluyor.",
        createdDate: "2024-02-05T18:49:22.067Z",
        user: {
          id: "u890123456",
          name: "Okan Yılmaz",
          email: "okan.yilmaz@gmail.com",
          emailVerified: null,
          image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png",
          hashedPassword: null,
          createdAt: "2023-06-17T11:38:29.979Z",
          updatedAt: "2023-06-17T11:38:29.979Z",
          role: "USER",
        },
      },
    ],
  },
  // {
  //   id: "15",
  //   name: "Maskara",
  //   description: "Kirpikleri uzatan ve dolgunlaştıran suya dayanıklı maskara",
  //   price: 79,
  //   brand: "Maybelline",
  //   category: "Makyaj",
  //   inStock: true,
  //   image: "https://images.unsplash.com/photo-1631214591073-adeed9c59f9a?auto=format&fit=crop&q=80",
  //   reviews: [],
  // },
  {
    id: "16",
    name: "Saç Kremi",
    description: "Kuru ve yıpranmış saçlar için onarıcı saç kremi. İçeriğindeki keratin ve argan yağı karışımı ile saç tellerinin yapısını derinlemesine onarır ve kırılmaları önler. Şampuandan sonra uygulanan yoğun nem kompleksi ile saçların elektriklenme ve kabarma sorunlarını giderir, kolay taranabilir ve şekillendirilebilir hale getirir. Isıyla şekillendirme sonucu zarar görmüş saçları korur ve saç uçlarındaki kırılmaları azaltır. Ağır olmayan formülü ile saçları ağırlaştırmadan nemlendirirken, içeriğindeki UV filtreleri ile güneş ışınlarına karşı da koruma sağlar.",
    price: 65,
    brand: "Pantene",
    category: "Saç Bakımı",
    inStock: true,
    image: "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&q=80",
    reviews: [
      {
        id: "r0y1z2a3b4c5",
        userId: "u901234567",
        productId: "16",
        rating: 5,
        comment: "Saçlarım artık çok daha yumuşak ve parlak. Çok az miktarda kullanmak yeterli oluyor.",
        createdDate: "2024-01-30T12:23:15.067Z",
        user: {
          id: "u901234567",
          name: "Tuğçe Aslan",
          email: "tugce.aslan@gmail.com",
          emailVerified: null,
          image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png",
          hashedPassword: null,
          createdAt: "2023-09-10T09:27:33.979Z",
          updatedAt: "2023-09-10T09:27:33.979Z",
          role: "USER",
        },
      },
    ],
  },
  // {
  //   id: "17",
  //   name: "C Vitamini Serumu",
  //   description: "Cilt tonunu eşitleyen ve aydınlatan C vitamini yüz serumu",
  //   price: 185,
  //   brand: "Vichy",
  //   category: "Cilt Bakımı",
  //   inStock: false,
  //   image: "https://images.unsplash.com/photo-1615897232510-bab54b115053?auto=format&fit=crop&q=80",
  //   reviews: [],
  // },
  {
    id: "18",
    name: "Dudak Balmı",
    description: "Kuru dudaklar için nemlendirici ve onarıcı dudak balmı. İçeriğindeki shea yağı ve E vitamini kurumuş, çatlamış dudakları anında nemlendirir ve yumuşatır. Doğal balmumu ile dudaklarda koruyucu bir bariyer oluşturarak nem kaybını önler ve rüzgar, soğuk gibi dış etkenlere karşı koruma sağlar. Hafif mentollü formülü dudaklarda ferahlık hissi verirken, içeriğindeki bitkisel yağlar ile dudakların doğal yumuşaklığını geri kazanmasına yardımcı olur. Renkli olanlarının parlak pigmenti ile dudaklara doğal bir parlaklık ve hafif bir renk tonu kazandırır.",
    price: 45,
    brand: "Burt's Bees",
    category: "Dudak Bakımı",
    inStock: true,
    image: "https://images.unsplash.com/photo-1600612253971-422e7f7faeb6?auto=format&fit=crop&q=80",
    reviews: [],
  },
  // {
  //   id: "19",
  //   name: "Allık",
  //   description: "Doğal ve canlı görünüm sağlayan toz allık",
  //   price: 110,
  //   brand: "NARS",
  //   category: "Makyaj",
  //   inStock: true,
  //   image: "https://images.unsplash.com/photo-1596704017254-9d9682713ea1?auto=format&fit=crop&q=80",
  //   reviews: [
  //     {
  //       id: "r6d7e8f9g0h1",
  //       userId: "u123789456",
  //       productId: "19",
  //       rating: 5,
  //       comment: "Bu allığın rengi çok doğal duruyor ve uzun süre kalıcı. Kesinlikle favorim!",
  //       createdDate: "2024-02-25T13:11:28.067Z",
  //       user: {
  //         id: "u123789456",
  //         name: "Ebru Kaya",
  //         email: "ebru.kaya@gmail.com",
  //         emailVerified: null,
  //         image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png",
  //         hashedPassword: null,
  //         createdAt: "2023-10-20T15:42:18.979Z",
  //         updatedAt: "2023-10-20T15:42:18.979Z",
  //         role: "USER",
  //       },
  //     },
  //     {
  //       id: "r2i3j4k5l6m7",
  //       userId: "u456123789",
  //       productId: "19",
  //       rating: 4,
  //       comment: "Rengi çok güzel ama fırçası biraz daha iyi olabilirdi. Yine de pişman değilim.",
  //       createdDate: "2024-03-17T09:47:36.067Z",
  //       user: {
  //         id: "u456123789",
  //         name: "Can Özdemir",
  //         email: "can.ozdemir@gmail.com",
  //         emailVerified: null,
  //         image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png",
  //         hashedPassword: null,
  //         createdAt: "2023-07-05T18:33:47.979Z",
  //         updatedAt: "2023-07-05T18:33:47.979Z",
  //         role: "USER",
  //       },
  //     },
  //     {
  //       id: "r8n9o0p1q2r3",
  //       userId: "u789456123",
  //       productId: "19",
  //       rating: 5,
  //       comment: "Bu allık özellikle bahar ve yaz ayları için harika bir renk. Tavsiye ederim.",
  //       createdDate: "2024-01-15T16:59:12.067Z",
  //       user: {
  //         id: "u789456123",
  //         name: "Sevgi Yıldırım",
  //         email: "sevgi.yildirim@gmail.com",
  //         emailVerified: null,
  //         image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png",
  //         hashedPassword: null,
  //         createdAt: "2023-08-28T14:19:53.979Z",
  //         updatedAt: "2023-08-28T14:19:53.979Z",
  //         role: "USER",
  //       },
  //     },
  //   ],
  // },
  // {
  //   id: "20",
  //   name: "El Kremi",
  //   description: "Kuru ve çatlamış eller için yoğun nemlendirici el kremi",
  //   price: 39,
  //   brand: "Neutrogena",
  //   category: "Vücut Bakımı",
  //   inStock: true,
  //   image: "https://images.unsplash.com/photo-1614859538834-0770df6d2e0d?auto=format&fit=crop&q=80",
  //   reviews: [
  //     {
  //       id: "r4s5t6u7v8w9",
  //       userId: "u321654987",
  //       productId: "20",
  //       rating: 5,
  //       comment: "Kışın ellerim çok çatlıyordu, bu krem sayesinde sorunum kalmadı. Hızlı emiliyor ve yapış yapış yapmıyor.",
  //       createdDate: "2024-02-10T20:31:42.067Z",
  //       user: {
  //         id: "u321654987",
  //         name: "Mert Aksoy",
  //         email: "mert.aksoy@gmail.com",
  //         emailVerified: null,
  //         image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png",
  //         hashedPassword: null,
  //         createdAt: "2023-11-25T11:58:24.979Z",
  //         updatedAt: "2023-11-25T11:58:24.979Z",
  //         role: "USER",
  //       },
  //     },
  //   ],
  // }
];