export const products = [
  {
    id: "1",
    name: "Nemlendirici Yüz Kremi",
    description: "Kuru ciltler için 24 saat nemlendirici etkili yüz kremi",
    price: 129,
    brand: "Neutrogena",
    category: "Cilt Bakımı",
    inStock: true,
    image: "https://images.unsplash.com/photo-1556229174-5e42a09e45af?auto=format&fit=crop&q=80",
    reviews: [],
  },
  {
    id: "2",
    name: "Mat Ruj",
    description: "Uzun süre kalıcı mat bitişli likit ruj",
    price: 89,
    brand: "MAC",
    category: "Makyaj",
    inStock: true,
    image: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&q=80",
    reviews: [],
  },
  {
    id: "3",
    name: "Güneş Koruyucu Krem SPF50",
    description: "Yüksek koruma faktörlü, suya dayanıklı güneş kremi",
    price: 149,
    brand: "La Roche-Posay",
    category: "Güneş Bakımı",
    inStock: true,
    image: "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&q=80",
    reviews: [],
  },
  {
    id: "4",
    name: "Sıkılaştırıcı Göz Serumu",
    description: "Göz çevresindeki ince çizgileri azaltan ve sıkılaştıran serum",
    price: 215,
    brand: "Clinique",
    category: "Cilt Bakımı",
    inStock: false,
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80",
    reviews: [],
  },
  // {
  //   id: "5",
  //   name: "Kapatıcı",
  //   description: "Kusurları ve göz altı morluklarını etkili şekilde kapatan kapatıcı",
  //   price: 95,
  //   brand: "Maybelline",
  //   category: "Makyaj",
  //   inStock: true,
  //   image: "https://images.unsplash.com/photo-1631730359585-38a358764614?auto=format&fit=crop&q=80",
  //   reviews: [],
  // },
  // {
  //   id: "6",
  //   name: "Arındırıcı Yüz Temizleme Jeli",
  //   description: "Gözenekleri arındıran ve yağlı cildi dengeleyen temizleme jeli",
  //   price: 79,
  //   brand: "Garnier",
  //   category: "Cilt Bakımı",
  //   inStock: true,
  //   image: "https://images.unsplash.com/photo-1633683395897-ed5f65c11992?auto=format&fit=crop&q=80",
  //   reviews: [],
  // },
  {
    id: "7",
    name: "Saç Bakım Serumu",
    description: "Yıpranmış saçlar için onarıcı ve güçlendirici etkili serum",
    price: 175,
    brand: "Kerastase",
    category: "Saç Bakımı",
    inStock: true,
    image: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&q=80",
    reviews: [],
  },
  // {
  //   id: "8",
  //   name: "Fondöten",
  //   description: "Doğal ve mat görünüm sağlayan uzun süre kalıcı fondöten",
  //   price: 159,
  //   brand: "Estee Lauder",
  //   category: "Makyaj",
  //   inStock: true,
  //   image: "https://images.unsplash.com/photo-1614159102522-26f8a9a3f98c?auto=format&fit=crop&q=80",
  //   reviews: [],
  // },
  // {
  //   id: "9",
  //   name: "Parfüm 50ml",
  //   description: "Çiçeksi ve odunsu notalar içeren uzun süre kalıcı kadın parfümü",
  //   price: 320,
  //   brand: "Chanel",
  //   category: "Parfüm",
  //   inStock: true,
  //   image: "https://images.unsplash.com/photo-1619994403073-2cec99c800d2?auto=format&fit=crop&q=80",
  //   reviews: [],
  // },
  {
    id: "10",
    name: "Erkek Parfüm 100ml",
    description: "Ferah ve baharatlı notalar içeren erkek parfümü",
    price: 280,
    brand: "Hugo Boss",
    category: "Parfüm",
    inStock: false,
    image: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&q=80",
    reviews: [],
  },
  {
    id: "11",
    name: "Göz Farı Paleti",
    description: "12 farklı renk içeren mat ve simli göz farı paleti",
    price: 199,
    brand: "Urban Decay",
    category: "Makyaj",
    inStock: true,
    image: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&q=80",
    reviews: [],
  },
  // {
  //   id: "12",
  //   name: "Akne Karşıtı Tonik",
  //   description: "Sivilce ve siyah noktalara karşı etkili arındırıcı tonik",
  //   price: 85,
  //   brand: "The Ordinary",
  //   category: "Cilt Bakımı",
  //   inStock: true,
  //   image: "https://images.unsplash.com/photo-1611080541675-61967df958e4?auto=format&fit=crop&q=80",
  //   reviews: [],
  // },
  // {
  //   id: "13",
  //   name: "Saç Şampuanı",
  //   description: "Boyalı saçlar için renk koruyucu ve besleyici şampuan",
  //   price: 69,
  //   brand: "L'Oreal",
  //   category: "Saç Bakımı",
  //   inStock: true,
  //   image: "https://images.unsplash.com/photo-1631730357933-93d4ce3715ff?auto=format&fit=crop&q=80",
  //   reviews: [],
  // },
  {
    id: "14",
    name: "Hyaluronik Asit Serum",
    description: "Yoğun nemlendirici etkili hyaluronik asit içeren yüz serumu",
    price: 125,
    brand: "The Ordinary",
    category: "Cilt Bakımı",
    inStock: true,
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80",
    reviews: [],
  },
  // {
  //   id: "15",
  //   name: "Maskara",
  //   description: "Kirpikleri uzatan ve dolgunlaştıran suya dayanıklı maskara",
  //   price: 79,
  //   brand: "Maybelline",
  //   category: "Makyaj",
  //   inStock: true,
  //   image: "https://images.unsplash.com/photo-1631214591073-adeed9c59f9a?auto=format&fit=crop&q=80",
  //   reviews: [],
  // },
  {
    id: "16",
    name: "Saç Kremi",
    description: "Kuru ve yıpranmış saçlar için onarıcı saç kremi",
    price: 65,
    brand: "Pantene",
    category: "Saç Bakımı",
    inStock: true,
    image: "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&q=80",
    reviews: [],
  },
  // {
  //   id: "17",
  //   name: "C Vitamini Serumu",
  //   description: "Cilt tonunu eşitleyen ve aydınlatan C vitamini yüz serumu",
  //   price: 185,
  //   brand: "Vichy",
  //   category: "Cilt Bakımı",
  //   inStock: false,
  //   image: "https://images.unsplash.com/photo-1615897232510-bab54b115053?auto=format&fit=crop&q=80",
  //   reviews: [],
  // },
  {
    id: "18",
    name: "Dudak Balmı",
    description: "Kuru dudaklar için nemlendirici ve onarıcı dudak balmı",
    price: 45,
    brand: "Burt's Bees",
    category: "Dudak Bakımı",
    inStock: true,
    image: "https://images.unsplash.com/photo-1600612253971-422e7f7faeb6?auto=format&fit=crop&q=80",
    reviews: [],
  },
//   {
//     id: "19",
//     name: "Allık",
//     description: "Doğal ve canlı görünüm sağlayan toz allık",
//     price: 110,
//     brand: "NARS",
//     category: "Makyaj",
//     inStock: true,
//     image: "https://images.unsplash.com/photo-1596704017254-9d9682713ea1?auto=format&fit=crop&q=80",
//     reviews: [],
//   },
//   {
//     id: "20",
//     name: "El Kremi",
//     description: "Kuru ve çatlamış eller için yoğun nemlendirici el kremi",
//     price: 39,
//     brand: "Neutrogena",
//     category: "Vücut Bakımı",
//     inStock: true,
//     image: "https://images.unsplash.com/photo-1614859538834-0770df6d2e0d?auto=format&fit=crop&q=80",
//     reviews: [],
//   }
];
